account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import (UserLoginForm)
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
]
 

basket/urls.py
from django.urls import path

from . import views

app_name ='basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update')

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views 

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('new_product/', views.new_product, name='new_product'),
    path('edition_product/', views.edition_product, name='edition_product'),
    ]   

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
    

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
           
    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="product_creator", default=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default="admin")
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/", default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()


    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
       
    def __str__(self):
        return self.title

store/forms.py
from django import forms
from django.forms import widgets
from .models import Product


class ArticuloForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ['title', 'image', 'description', 'price', 'category']
        labels={
            'title': 'Titulo',
            'image': 'Imagen',
            'description': 'Descripción',
            'category': 'Categoria',
            'price': 'Precio',
        }

        widgets= {
            'description': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción'}),
            'title': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Título de producto'})
        }

class UpdateArticuloForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ['title', 'image', 'description', 'price', 'category']
        labels={
            'title': 'Titulo',
            'image': 'Imagen',
            'description': 'Descripción',
            'category': 'Categoria',
            'price': 'Precio',
        }

        widgets= {
            'description': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción'}),
            'title': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Título de producto'})
        }    
    def save(self):
        product = self.instance
        product.title = self.cleaned_data['Titulo']
        product.description = self.cleaned_data['Descripcion']
        product.category = self.cleaned_data['Categoria']
        product.price = self.cleaned_data['Precio']

        if self.clenead_data['image']:
            image = self.cleaned_data['Imagen']
        product.save()
        return product

store/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Category, Product  
from django.db.models import Q
from django.db.models import query
from django import forms
from .forms import *
from django.contrib import messages

product = Product.objects.all()

productWhithImage= []
productWhithoutImage= []
for i in range(10):
    if (i <= 2):
        productWhithImage.append(product[i])
    else:
        productWhithoutImage.append(product[i])

def product_all (request):
    list_productimage = Product.objects.all().order_by("-id")[:3]
    list_productSinimage = Product.objects.all().order_by("-id")[3:10]

    def get(self, request, *args, **kwargs):
            return render (request, self.template_name, {"self.list_productimage": list_productimage, "self.list_productSinimage": list_productSinimage})
    
    return render(request, 'store/home.html', {
            "list_productimage": productWhithImage,
            "list_productSinimage": productWhithoutImage,
        })


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def about(request):
    return render(request, "store/about.html")


def contact(request):
    return render(request, "store/contact.html")
    

def search(request):    
    query=None
    results=[]
    if request.method == "GET":
        query = request.GET.get('search')
        results = Product.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return render(request, 'store/search.html', {'query': query, 'results':results})
    else:
        return render(request, 'store/search.html')
      

def new_product(request):
    if request.method == 'POST':
        form = ArticuloForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Producto creado con exito')
            return redirect('store:new_product') 
    else:       
        form = ArticuloForm()
    return render(
        request=request,
        template_name='store/new_product.html',
        context={'agregar': form})


def edition_product(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        form = UpdateArticuloForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('/')         
    else:
        form = UpdateArticuloForm(instance=product)
        return render(request, 'store/edition_product.html'), {'product': product, 'form': form }

def delete_product_db(request, product_id):
    product= Product.objects.get(id=product_id)
    product.delete()
    messages.succes(request, 'Producto eliminado')
    return redirect('home')

templates/store/about.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Acerca de Nosotros{% endblock %}
{% block content %}

<style>
h1{
  text-align: center;  
}

p{
    margin-top: 15px;
    text-align: justify;
}

.img-us{
  width: 100%;
  height: 100%;;
}


</style>

<main class="px-3">
    <h1>Nosotros</h1>
    <br>
    <p class="lead">Jaguarete Akk es nuestra empresa familiar, inspirada por la moda, el hogar y la vida cotidiana. Integrando el amor y las posibilidades tecnológicas, creamos esta plataforma para que más gente pueda comprar desde la comodidad de sus casas en cualquier lado del país. Este año pudimos abrir nuestra primer local. Felices de poder seguir creciendo. Los esperamos!. 
    </p>
    <br>
    <img class="img-us" src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/419/788/themes/style/slide-1615419459044-2951529869-b800a89534299845d83f0574b534762d1615419466-1920-1920.png?1835459248">
    
  </main>

{% endblock %}

templates/store/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Tienda de Espejos{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
    integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
  <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}">
</head>

<style>
body{
  margin-left: 10%;
  margin-right: 10%;
  }

</style>

<body>

  <div class="b-example-divider"></div>

  <header class="pb-3">
    <div class="container-fluid">
      <a href="/">
          <img id="logo"
          src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/419/788/themes/style/img-310053922-1605499605-0c8cb140602709757c1e0849971cb71b1605499605.png?1560115928"
          alt="mdo" class="rounded-circle">
      </a>
      <ul class="nav" style= "float: right">

            {% if user.is_authenticated %}

            <li class="nav-item">             
            <a type= "button" role="button" href="{% url "account:logout" %}" class="btn btn-outline-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
              <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
              <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z"/>
              </svg>Logout</a>  
            </li>

             {% else %}

              <li class="nav-item">             
            <a type= "button" role="button" href="{% url "account:login" %}" class="btn btn-outline-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
              <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
              <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z"/>
              </svg>Login</a>  
            </li>

              {% endif %}

            <li class="nav-item"><a type= "button" role="button" href="{% url "account:register" %}" class="btn btn-outline-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
             <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>Registro</a></li>



            <li class="nav-item">
              <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-outline-secondary">

              {% with total_qty=basket|length %}
                <div id="basket-qty" class="d-inline-flex">
                   {% if total_qty > 0 %}
                      {{ total_qty }}
                    {% else %}
                       0
                   {% endif %}
                </div>
              {% endwith %}


              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>Carrito</a></li>
            
          </ul>
    </div>
    <nav id="navegador" class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a href="/" class="nav-link link-dark px-2 active" aria-current="page">Inicio</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">Categorias</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url "store:product_all" %}">Todas</a></li>
              {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
            </li>
              {% endfor %}
          </ul>
            </li>
            <li class="nav-item"><a href="{% url 'store:about' %}" class="nav-link link-dark px-2">Acerca de</a></li>
            <li class="nav-item"><a href="{% url 'store:contact' %}" class="nav-link link-dark px-2">Contacto</a></li>
           
            {% if user.is_authenticated and request.user.is_staff%}
            <li class="nav-item"><a href="{% url 'store:new_product' %}" class="nav-link link-dark px-2">Nuevo producto</a></li>
             {% endif %}
          </ul>
          <form class="d-flex" method="get" action="{% url 'store:search' %}">
          {% csrf_token %}
            <input type="search" class="form-control me-2y" placeholder="Buscar..." aria-label="search" name="search">
            <div class="btn-group">
              <button type="submit" class="btn btn-outline-secondary"><i class="icon-search"></i>Buscar</button> 
            </div>
          </form>   
      </div>    
      </div>
    </nav>
  </header>

  <div id="content">{% block content%} {% endblock %}</div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">JAGUARETE KAA &copy; Lucia Riani</p>
  </footer>
</body>

</html>

templates/store/contact.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Contacto{% endblock %}
{% block content %}

<main class="px-3">
    <h1>Contacto</h1>
    <br>
    <p>Por cualquier duda o consulta comunicate con nosotros vía mail</p>
    <a class="mail-contac" href="mailto:admin@jagua.com.ar">Contáctanos por correo</a>
  </main>
{% endblock %}

templates/store/edition_product.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class= "col-md-5 col-lg-5 order-md-first bg-ligth">
                <form action="" method="post" enctype=multipart/form-data>
                {% csrf_token %}
                <img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image" src="{{ product.image.url }}">
                <div>{{ArticuloForm.image.label}}</div>
                <div>{{ArticuloForm.image}}</div>
            </div>
            <div class= "col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <div="mb-0 h4">{{ ArticuloForm.title.label }}</div>
                <div>{{ ArticuloForm.title }}</div>
                <br>
                <div>{{ ArticuloForm.description.label }}</div>
                <div>{{ ArticuloForm.descripcion }}</div>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Precio</div>
                            <div class="col-6 text-end">${{ ArticuloForm.price.label }}</div>
                            <div>{{ ArticuloForm.price }}</div>
                        </div>
                    </div>
                        <div class="col-6 text-end">
                        <input class="button btn-outline-succes" type="submit" value="Editar"></input>
                        <a href="{% product.id %}" class="btn btn-ouline-succes">Borrar</a>
                        </div>
                    </div>
                    
                </div>
            </div>        
        </div>
    </main>

</div>

{% endblock %}

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Tienda de Espejos{% endblock %}

{% block content%}

<style>
.img-fluid{
  max-width: 80%;
  height: auto;
  margin-left: 10%;
}
p{
  text-align:center;
}
</style>

<body>

  <div class="album py-5">
    <div class="container-fluid">

      <div class= "pb-3">
      </div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in list_productimage %}

        <div class="col">
          <div class="card border-0">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body px-0">
              <p class="card-text">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}...</a>
              </p>
              <div style="text-align:center"; class="fw-bold">${{product.price}}</div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
        <div class="moreproducts">
          <div class="container-center">
          <p style="font-size: 40px";>Más productos</p>
          <br>
          <ul>
              {% for product in list_productSinimage %}
                <div class="list-group">
                  <a href="{{ product.get_absolute_url }}" class="list-group-item active" style="background-color: white ! important;">
                  <h4 style="color:black"; class="list-group-item-heading">{{ product.title }}</h4>
                  <p style="color:black"; class="list-group-item-text">{{ product.description }}</p>
                  </a>
                </div>
              {% endfor %}
          </ul>
          </div>
        </div>            
        
      
    </div>
  </div>   

</body> 

{% endblock %}

templates/store/new_product.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}

<body>
    {% load crispy_forms_tags %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ agregar|crispy }}   
    <button type="btn btn-outline-success" value="{{ product.id}}">Agregar Producto</button>
    </form>
</body>


{% endblock %}

templates/store/search.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Buscador{% endblock %}


{% block content%}
    <justify>
    {% if query %}
    <h1>Listado de productos "{{ query }}"</h1>
            <h3>
            {% with results.count as total_results %}
            Encontré {{ total_results }} resultado{{ total_results|pluralize }}
            {% endwith %}
            </h3>
        {% for c in results %}
        <a herf="{{c.get_absolute_url}}"><h3>{{c.title}} - {{c.description}}</h3></a>
       
        
        {% empty %}
        <h4>No hay resultados para tu búsqueda</h4>
        {% endfor %}

    {% endif %}
    <justify>
{% endblock %}