basket/urls.py
from django.urls import path

from . import views

app_name ='basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update')

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views 

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('new_product/', views.new_product, name='new_product'),
    path('edition_product/', views.edition_product, name='edition_product'),
    ]   

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
    

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
           
    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="product_creator", default=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default="admin")
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/", default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()


    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
       
    def __str__(self):
        return self.title

store/forms.py
from django import forms
from django.forms import widgets
from .models import Product


class ArticuloForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ['title', 'image', 'description', 'price', 'category']
        labels={
            'title': 'Titulo',
            'image': 'Imagen',
            'description': 'Descripción',
            'category': 'Categoria',
            'price': 'Precio',
        }

        widgets= {
            'description': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción'}),
            'title': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Título de producto'})
        }

class UpdateArticuloForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ['title', 'image', 'description', 'price', 'category']
        labels={
            'title': 'Titulo',
            'image': 'Imagen',
            'description': 'Descripción',
            'category': 'Categoria',
            'price': 'Precio',
        }

        widgets= {
            'description': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción'}),
            'title': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Título de producto'})
        }    
    def save(self):
        product = self.instance
        product.title = self.cleaned_data['Titulo']
        product.description = self.cleaned_data['Descripcion']
        product.category = self.cleaned_data['Categoria']
        product.price = self.cleaned_data['Precio']

        if self.clenead_data['image']:
            image = self.cleaned_data['Imagen']
        product.save()
        return product

store/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Category, Product  
from django.db.models import Q
from django.db.models import query
from django import forms
from .forms import *
from django.contrib import messages

product = Product.objects.all()

productWhithImage= []
productWhithoutImage= []
for i in range(10):
    if (i <= 2):
        productWhithImage.append(product[i])
    else:
        productWhithoutImage.append(product[i])

def product_all (request):
    list_productimage = Product.objects.all().order_by("-id")[:3]
    list_productSinimage = Product.objects.all().order_by("-id")[3:10]

    def get(self, request, *args, **kwargs):
            return render (request, self.template_name, {"self.list_productimage": list_productimage, "self.list_productSinimage": list_productSinimage})
    
    return render(request, 'store/home.html', {
            "list_productimage": productWhithImage,
            "list_productSinimage": productWhithoutImage,
        })


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def about(request):
    return render(request, "store/about.html")


def contact(request):
    return render(request, "store/contact.html")
    

def search(request):    
    query=None
    results=[]
    if request.method == "GET":
        query = request.GET.get('search')
        results = Product.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return render(request, 'store/search.html', {'query': query, 'results':results})
    else:
        return render(request, 'store/search.html')
      

def new_product(request):
    if request.method == 'POST':
        form = ArticuloForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Producto creado con exito')
            return redirect('store:new_product') 
    else:       
        form = ArticuloForm()
    return render(
        request=request,
        template_name='store/new_product.html',
        context={'agregar': form})


def edition_product(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        form = UpdateArticuloForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('/')         
    else:
        form = UpdateArticuloForm(instance=product)
        return render(request, 'store/edition_product.html'), {'product': product, 'form': form }

def delete_product_db(request, product_id):
    product= Product.objects.get(id=product_id)
    product.delete()
    messages.succes(request, 'Producto eliminado')
    return redirect('home')

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content%}

<style>
.img-fluid{
  width: 70%;
  height: 70%;
  margin-left: 10%;
}
</style>

<div class="album py-5">
    <div class="container-fluid">

      <div class= "pb-3 h5">{{category.name|title}}</div>   
      <div class="row row-col-xs-4">

        {% for product in products %}

        <div class="col">
          <div class="card border-0">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">                          
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
        
      </div>
    </div>
</div>    
      
{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class= "col-md-5 col-lg-5 order-md-first bg-ligth">
                <img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class= "col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <br>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Precio</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                <div class="col">
                    <div class="row p-3">
                        <div class="col-6">
                            <label for="select">Cantidad</label>
                            <select id="select">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                        <div class="col-6 text-end">
<button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Agregar al carrito</button></div>
                    </div>
                </div>
            </div>        
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function(json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
})
</script>

{% endblock %}